### ISSUE TITLE
El futuro de los apuntes

### ISSUE THREAD

**Issue by ManuelBlanc** [apuntes-uam-infomat/Apuntes#94]
Hola,
soy un alumno de infomates en mi ultimo anyo de carrera. Los apuntes me han sido de gran ayuda para aprobar unas cuantas asignaturas. Gracias por haber hecho este proyecto! :)

Abro este hilo porque el ritmo de contribuciones ha perdido algo velocidad desde la graduacion de muchos (todos?) los autores originales. A continuacion hago dos propuestas para darle un poco de empujon al repositorio y abrirlo un poco mas:

#### Transferir el repositorio a una organizacion

Facilitaria "pasar la antorcha" cada anyo, desligandolo un poco de una sola (o grupo de) personas.
Tambien tiene la ventaja de que podrian agrupar utilidades relacionadas (como [gjulianm/latex_cd](https://github.com/gjulianm/latex_cd), y posiblemente separar `Cosas guays LaTeX/` en un paquete reusable de estilos/clases de LaTeX y otras utilidades.

#### Nombrar un equipo de encargados

Serian los encargados de responder pull requests, hacer mantenimiento, y quiza publicitar un poco los apuntes por la UAM.

Yo podria ofrecerme como voluntario para formar parte de este grupo durante 1 anyo.

---
Que opinais? Que os parece?

**Comment by gjulianm** [comment]
Comento tarde pero lo de la organización me parece una idea genial. Voy a empezar a moverlo a ver si lo podemos montar.

**Comment by VicdeJuan** [comment]
¡Transferido a la organización!
Perdonad que hayamos tardado tanto. ¡Muchas gracias!

**Comment by gjulianm** [comment]
Yo acabo de transferir el repositorio de latex_cd también. @ManuelBlanc, deberías de tener acceso administrador a la organización, para que puedas añadir a otros compañeros/as que quieran participar en los apuntes.

**Comment by manso92** [comment]
A lo mejor deberíamos pasar la gente que está en admin del repo de apuntes a miembros de la organización

**Comment by manso92** [comment]
Creo que sobre este tema ya se han llevado a cabo todo lo de la issue, paso a cerrarla.
